title:              The Hong Briefing
email:              shevril@gmail.com
description:        Simple words. Hard truths. What the mainstream misses about the global economy.
author:             YANG HONG
baseurl:            ""
url:                "https://yanghong1206.github.io"

# Social Profiles
twitter_username:   S/
github_username:    /
facebook_username:  S/
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
